# Generated by Django 3.2.16 on 2023-11-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscription_price_without_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='price_without_discount',
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
