# Generated by Django 3.2.16 on 2023-11-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20231109_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='data_modified',
            field=models.CharField(default='', max_length=30),
        ),
    ]
